import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { WalletConnections } from "@/components/WalletImports/page";
import { AuroraBackground } from "@/components/ui/aurora-background/aurora-background";
import { NavbarMenu } from "@/components/Navbar/Navbar";
import { LoadingProvider } from "@/hooks/LoadingProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Solana Wallet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuroraBackground>
          <LoadingProvider>
            <NavbarMenu />
            <WalletConnections>{children}</WalletConnections>
          </LoadingProvider>
        </AuroraBackground>
      </body>
    </html>
  );
}
